/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liang_example_nativeremote_RemoteManager */

#ifndef _Included_com_liang_example_nativeremote_RemoteManager
#define _Included_com_liang_example_nativeremote_RemoteManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liang_example_nativeremote_RemoteManager
 * Method:    startRemoteClient
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_liang_example_nativeremote_RemoteManager_startRemoteClient
        (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_liang_example_nativeremote_RemoteManager
 * Method:    stopRemoteClient
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_liang_example_nativeremote_RemoteManager_stopRemoteClient
        (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
