/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liang_example_nativeremote_AbsRemoteMsgHandler */

#ifndef _Included_com_liang_example_nativeremote_AbsRemoteMsgHandler
#define _Included_com_liang_example_nativeremote_AbsRemoteMsgHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liang_example_nativeremote_AbsRemoteMsgHandler
 * Method:    send
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_liang_example_nativeremote_AbsRemoteMsgHandler_send__Ljava_lang_Object_2
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_liang_example_nativeremote_AbsRemoteMsgHandler
 * Method:    send
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liang_example_nativeremote_AbsRemoteMsgHandler_send__Ljava_lang_String_2
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
